/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Line;
import backend.MiniPaint;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Asser Hanafy
 */
public class LinePropertiesWindow extends javax.swing.JDialog {

    private Color color;
    private Panel canvas;
    private MiniPaint paint;
    private boolean successful;

    /**
     * Creates new form CirclePropertiesWindow
     */
    public LinePropertiesWindow(Panel canvas, MiniPaint paint) {
        initComponents();
        this.canvas = canvas;
        this.paint = paint;
        successful = false;
        setModal(true);
    }
    
    public boolean isSuccessful() {
        return successful;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPointLabel = new javax.swing.JLabel();
        inputStartPointY = new javax.swing.JTextField();
        endPointLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        inputEndPointY = new javax.swing.JTextField();
        inputStartPointX = new javax.swing.JTextField();
        inputEndPointX = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        colorButton = new javax.swing.JButton();
        startXLabel = new javax.swing.JLabel();
        startYLabel = new javax.swing.JLabel();
        endXLabel = new javax.swing.JLabel();
        endYLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Line Properties");
        setResizable(false);

        startPointLabel.setText("Start Point");

        inputStartPointY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStartPointYActionPerformed(evt);
            }
        });

        endPointLabel.setText("End Point");

        colorLabel.setText("Color");

        inputEndPointY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEndPointYActionPerformed(evt);
            }
        });

        inputStartPointX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStartPointXActionPerformed(evt);
            }
        });

        inputEndPointX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEndPointXActionPerformed(evt);
            }
        });

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        colorButton.setText(" ");
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        startXLabel.setText("X");

        startYLabel.setText("Y");

        endXLabel.setText("X");

        endYLabel.setText("Y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startPointLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(startXLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputStartPointX, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(startYLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputStartPointY, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(colorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(endPointLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(endXLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputEndPointX, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(endYLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputEndPointY, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(colorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startPointLabel)
                    .addComponent(inputStartPointY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputStartPointX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startXLabel)
                    .addComponent(startYLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endPointLabel)
                    .addComponent(inputEndPointY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputEndPointX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endXLabel)
                    .addComponent(endYLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLabel)
                    .addComponent(colorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputStartPointYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStartPointYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputStartPointYActionPerformed

    private void inputEndPointYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEndPointYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEndPointYActionPerformed

    private void inputStartPointXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStartPointXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputStartPointXActionPerformed

    private void inputEndPointXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEndPointXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEndPointXActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        String startPointX = inputStartPointX.getText().strip();
        String startPointY = inputStartPointY.getText().strip();
        String endPointX = inputEndPointX.getText().strip();
        String endPointY = inputEndPointY.getText().strip();
        if (startPointX.equals("") || startPointY.equals("") || endPointX.equals("") || endPointY.equals("") || color == null) {
            JOptionPane.showMessageDialog(this, "Some fields are empty!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Point startPoint = new Point();
                Point endPoint = new Point();
                startPoint.x = Integer.parseInt(startPointX);
                startPoint.y = Integer.parseInt(startPointY);
                endPoint.x = Integer.parseInt(endPointX);
                endPoint.y = Integer.parseInt(endPointY);
                if (startPoint.x < 0 || startPoint.y < 0 || endPoint.x < 0 || endPoint.y < 0) {
                    throw new Exception("You should enter valid numbers!");
                } else if (startPoint.x > canvas.getWidth() || startPoint.y > canvas.getHeight() || endPoint.x > canvas.getWidth() || endPoint.y > canvas.getHeight()) {
                    throw new Exception("Coordinates out of bound! [length=425,width=250]");
                }
                Line line = new Line(startPoint, endPoint);
                line.setPosition(startPoint);
                line.setColor(color);
//                line.draw(canvas.getGraphics());
                paint.addShape(line);
                successful = true;
                this.dispose();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "You should enter valid numbers!", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_createActionPerformed

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        color = JColorChooser.showDialog(this, "Select a color", Color.white);
        colorButton.setBackground(color);
    }//GEN-LAST:event_colorButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colorButton;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JButton create;
    private javax.swing.JLabel endPointLabel;
    private javax.swing.JLabel endXLabel;
    private javax.swing.JLabel endYLabel;
    private javax.swing.JTextField inputEndPointX;
    private javax.swing.JTextField inputEndPointY;
    private javax.swing.JTextField inputStartPointX;
    private javax.swing.JTextField inputStartPointY;
    private javax.swing.JLabel startPointLabel;
    private javax.swing.JLabel startXLabel;
    private javax.swing.JLabel startYLabel;
    // End of variables declaration//GEN-END:variables
}
