/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Line;
import backend.MiniPaint;
import backend.Shape;
import java.awt.Point;
import javax.swing.JOptionPane;

/**
 *
 * @author Asser Hanafy
 */
public class MoveWindow extends javax.swing.JDialog {

    private Panel canvas;
    private MiniPaint paint;
    private int index;

    /**
     * Creates new form CirclePropertiesWindow
     */
    public MoveWindow(Panel canvas, MiniPaint paint, int index) {
        initComponents();
        this.canvas = canvas;
        this.paint = paint;
        this.index = index;
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionLabel = new javax.swing.JLabel();
        inputPositionY = new javax.swing.JTextField();
        radiusLabel = new javax.swing.JLabel();
        move = new javax.swing.JButton();
        inputPositionX = new javax.swing.JTextField();
        XLabel = new javax.swing.JLabel();
        YLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Move Shape");
        setResizable(false);

        positionLabel.setText("Enter New X");

        inputPositionY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPositionYActionPerformed(evt);
            }
        });

        radiusLabel.setText("Enter New Y");

        move.setText("Move Shape");
        move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveActionPerformed(evt);
            }
        });

        inputPositionX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPositionXActionPerformed(evt);
            }
        });

        XLabel.setText("X");

        YLabel.setText("Y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(positionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(XLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radiusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(YLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPositionX, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPositionY, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(move, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLabel)
                    .addComponent(inputPositionX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(XLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiusLabel)
                    .addComponent(inputPositionY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(move, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputPositionYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPositionYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPositionYActionPerformed

    private void moveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveActionPerformed
        String positionX = inputPositionX.getText().strip();
        String positionY = inputPositionY.getText().strip();
        if (positionX.equals("") || positionY.equals("")) {
            JOptionPane.showMessageDialog(this, "Some fields are empty!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Point position = new Point();
                position.x = Integer.parseInt(positionX);
                position.y = Integer.parseInt(positionY);
                if (position.x < 0 || position.y < 0) {
                    throw new Exception("You should enter valid numbers");
                } else if (position.x > canvas.getWidth() || position.y > canvas.getHeight()) {
                    throw new Exception("Coordinates out of bound! [length=425,width=250]");
                }
                Shape[] shapes = paint.getShapes();
                Shape shape = shapes[index];
                if (shape instanceof Line) {
                    Point point = shape.getPosition();
                    int diffX = position.x - point.x;
                    int diffY = position.y - point.y;
                    point = ((Line) shape).getEndPoint();
                    Point newPoint = new Point(point.x + diffX, point.y + diffY);
                    ((Line) shape).setEndPoint(newPoint);
                }
                shape.setPosition(position);
                this.dispose();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "You should enter valid numbers", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_moveActionPerformed

    private void inputPositionXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPositionXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPositionXActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel XLabel;
    private javax.swing.JLabel YLabel;
    private javax.swing.JTextField inputPositionX;
    private javax.swing.JTextField inputPositionY;
    private javax.swing.JButton move;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JLabel radiusLabel;
    // End of variables declaration//GEN-END:variables
}
