/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Line;
import backend.MiniPaint;
import backend.Shape;
import java.awt.Point;
import javax.swing.JOptionPane;

/**
 *
 * @author Asser Hanafy
 */
public class ResizeLineWindow extends javax.swing.JDialog {

    private Panel canvas;
    private MiniPaint paint;
    private int index;

    /**
     * Creates new form CirclePropertiesWindow
     */
    public ResizeLineWindow(Panel canvas, MiniPaint paint, int index) {
        initComponents();
        this.canvas = canvas;
        this.paint = paint;
        this.index = index;
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionLabel = new javax.swing.JLabel();
        resize = new javax.swing.JButton();
        inputPositionX = new javax.swing.JTextField();
        positionLabel1 = new javax.swing.JLabel();
        inputPositionY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resize Line");
        setResizable(false);

        positionLabel.setText("Enter New X2");

        resize.setText("Resize Line");
        resize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeActionPerformed(evt);
            }
        });

        inputPositionX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPositionXActionPerformed(evt);
            }
        });

        positionLabel1.setText("Enter New Y2");

        inputPositionY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPositionYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(resize, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(positionLabel)
                    .addComponent(positionLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPositionX, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPositionY, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLabel)
                    .addComponent(inputPositionX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLabel1)
                    .addComponent(inputPositionY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(resize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeActionPerformed
        String positionX = inputPositionX.getText().strip();
        String positionY = inputPositionY.getText().strip();
        if (positionX.equals("") || positionY.equals("")) {
            JOptionPane.showMessageDialog(this, "Some fields are empty!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Point position = new Point();
                position.x = Integer.parseInt(positionX);
                position.y = Integer.parseInt(positionY);
                if (position.x < 0 || position.y < 0) {
                    throw new Exception("You should enter valid numbers!");
                } else if (position.x > canvas.getWidth() || position.y > canvas.getHeight()) {
                    throw new Exception("Coordinates out of bound! [length=425,width=250]");
                }
                Shape[] shapes = paint.getShapes();
                Shape shape = shapes[index];
                ((Line) shape).setEndPoint(position);
                this.dispose();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "You should enter valid numbers!", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_resizeActionPerformed

    private void inputPositionXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPositionXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPositionXActionPerformed

    private void inputPositionYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPositionYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPositionYActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputPositionX;
    private javax.swing.JTextField inputPositionY;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JLabel positionLabel1;
    private javax.swing.JButton resize;
    // End of variables declaration//GEN-END:variables
}
