/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.MiniPaint;
import backend.Shape;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Asser Hanafy
 */
public class ResizeCircleWindow extends javax.swing.JDialog {

    private MiniPaint paint;
    private int index;

    /**
     * Creates new form CirclePropertiesWindow
     */
    public ResizeCircleWindow(MiniPaint paint, int index) {
        initComponents();
        this.paint = paint;
        this.index = index;
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionLabel = new javax.swing.JLabel();
        resize = new javax.swing.JButton();
        inputRadius = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resize Circle");
        setResizable(false);

        positionLabel.setText("Enter New Radius");

        resize.setText("Resize Circle");
        resize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeActionPerformed(evt);
            }
        });

        inputRadius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRadiusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(positionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(inputRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(resize, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLabel)
                    .addComponent(inputRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(resize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeActionPerformed
        String radiusText = inputRadius.getText().strip();
        if (radiusText.equals("")) {
            JOptionPane.showMessageDialog(this, "Field is empty!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                double radius = Double.parseDouble(radiusText);
                if (radius < 0) {
                    throw new Exception("You should enter a valid number!");
                }
                Shape[] shapes = paint.getShapes();
                Shape shape = shapes[index];
                shape.setProperties(Map.of("radius", radius));
                this.dispose();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "You should enter a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_resizeActionPerformed

    private void inputRadiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRadiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRadiusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputRadius;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JButton resize;
    // End of variables declaration//GEN-END:variables
}
