/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.MiniPaint;
import backend.Square;
import java.awt.Color;
import java.awt.Point;
import java.util.Map;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Asser Hanafy
 */
public class SquarePropertiesWindow extends javax.swing.JDialog {
    
    private Color color;
    private Color fillColor;
    private Panel canvas;
    private MiniPaint paint;
    private boolean successful;
    /**
     * Creates new form CirclePropertiesWindow
     */
    public SquarePropertiesWindow(Panel canvas, MiniPaint paint) {
        initComponents();
        this.canvas = canvas;
        this.paint = paint;
        successful = false;
        setModal(true);
    }
    
    public boolean isSuccessful() {
        return successful;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionLabel = new javax.swing.JLabel();
        inputPositionY = new javax.swing.JTextField();
        lengthLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        fillColorLabel = new javax.swing.JLabel();
        inputLength = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        inputPositionX = new javax.swing.JTextField();
        XLabel = new javax.swing.JLabel();
        YLabel = new javax.swing.JLabel();
        colorButton = new javax.swing.JButton();
        fillColorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Square Properties");
        setResizable(false);

        positionLabel.setText("Position");

        inputPositionY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPositionYActionPerformed(evt);
            }
        });

        lengthLabel.setText("Length");

        colorLabel.setText("Color");

        fillColorLabel.setText("Fill Color (Optional)");

        inputLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLengthActionPerformed(evt);
            }
        });

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        inputPositionX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPositionXActionPerformed(evt);
            }
        });

        XLabel.setText("X");

        YLabel.setText("Y");

        colorButton.setText(" ");
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        fillColorButton.setText(" ");
        fillColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(positionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(XLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPositionX, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(YLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPositionY, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lengthLabel)
                            .addComponent(colorLabel)
                            .addComponent(fillColorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fillColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(colorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputLength, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLabel)
                    .addComponent(inputPositionY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPositionX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(XLabel)
                    .addComponent(YLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthLabel)
                    .addComponent(inputLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLabel)
                    .addComponent(colorButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fillColorLabel)
                    .addComponent(fillColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputPositionYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPositionYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPositionYActionPerformed

    private void inputLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLengthActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        String positionX = inputPositionX.getText().strip();
        String positionY = inputPositionY.getText().strip();
        String lengthStr = inputLength.getText().strip();
        if (positionX.equals("") || positionY.equals("") || lengthStr.equals("") || color == null) {
            JOptionPane.showMessageDialog(this, "Some fields are empty!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Point position = new Point();
                position.x = Integer.parseInt(positionX);
                position.y = Integer.parseInt(positionY);
                double length = Double.parseDouble(lengthStr);
                if (position.x < 0 || position.y < 0 || length < 0) {
                    throw new Exception("You should enter valid numbers!");
                } else if (position.x > canvas.getWidth() || position.y > canvas.getHeight()) {
                    throw new Exception("Coordinates out of bound! [length=425,width=250]");
                }
                Square square = new Square(length);
                square.setPosition(position);
                square.setProperties(Map.of("length", length));
                square.setColor(color);
                square.setFillColor(fillColor);
//                square.draw(canvas.getGraphics());
                paint.addShape(square);
                successful = true;
                this.dispose();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "You should enter valid numbers!", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_createActionPerformed

    private void inputPositionXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPositionXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPositionXActionPerformed

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        color = JColorChooser.showDialog(this, "Select a color", Color.white);
        colorButton.setBackground(color);
    }//GEN-LAST:event_colorButtonActionPerformed

    private void fillColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColorButtonActionPerformed
        fillColor = JColorChooser.showDialog(this, "Select a fill color", Color.white);
        fillColorButton.setBackground(fillColor);
    }//GEN-LAST:event_fillColorButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel XLabel;
    private javax.swing.JLabel YLabel;
    private javax.swing.JButton colorButton;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JButton create;
    private javax.swing.JButton fillColorButton;
    private javax.swing.JLabel fillColorLabel;
    private javax.swing.JTextField inputLength;
    private javax.swing.JTextField inputPositionX;
    private javax.swing.JTextField inputPositionY;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JLabel positionLabel;
    // End of variables declaration//GEN-END:variables
}
